weights: yolov5s.pt
cfg: ''
data: data/sirst.yaml
hyp:
  anchor_t: 4.0
  box: 0.05
  cls: 0.0
  cls_pw: 1.0
  copy_paste: 0.0
  degrees: 0.0
  fl_gamma: 0.0
  fliplr: 1.0
  flipud: 0.0
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.2
  iou_t: 0.2
  lr0: 0.003
  lrf: 0.01
  mixup: 0.0
  momentum: 0.937
  mosaic: 0.0
  obj: 1.0
  obj_pw: 1.0
  perspective: 0.0
  scale: 0.0
  shear: 0.0
  translate: 0.0
  warmup_bias_lr: 0.1
  warmup_epochs: 2.0
  warmup_momentum: 0.8
  weight_decay: 0.0005
epochs: 100
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: yolov5_sirst_augmented
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 15
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: runs/train/yolov5_sirst_augmented
